<?
session_start();
session_destroy();
$verified_pass="";
$verified_user="";
$verified_yonid="";
$KulEkle="";
$_SESSION['verified_pass']=$verified_pass;
//session_register("verified_pass");
$_SESSION['verified_user']=$verified_user;
//session_register("verified_user");
$_SESSION['verified_yonid']=$verified_yonid;
//session_register("verified_yonid");
$_SESSION['KulEkle']=$KulEkle;
//session_register("KulEkle");
unset($_SESSION['verified_pass']);
//session_unregister("verified_pass");
unset($_SESSION['verified_user']);
//session_unregister("verified_user");
unset($_SESSION['verified_yonid']);
//session_unregister("verified_yonid");
unset($_SESSION['KulEkle']);
//session_unregister("KulEkle");
header("location:index.php");

?>
