apply plugin: 'com.android.application'

android {
    compileSdkVersion 30

    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "com.asgulec.tekliftopla"
        minSdkVersion 15
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
        }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }
    //ASG
    dexOptions {
        preDexLibraries = false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.fragment:fragment:1.4.0-alpha05'

    implementation 'com.roomorama:caldroid:3.0.1'
    implementation "androidx.core:core-ktx:1.6.0"
    implementation 'com.facebook.android:facebook-core:11.1.1'
    implementation 'com.facebook.android:facebook-login:11.1.1'
    implementation 'com.facebook.android:facebook-android-sdk:11.1.1'
    implementation 'com.google.android.gms:play-services-auth:19.2.0'
    implementation 'com.google.android.gms:play-services-games:21.0.0'
    implementation 'com.google.android.gms:play-services-location:18.0.0'
    implementation 'com.android.volley:volley:1.2.0'
}
repositories {
    mavenCentral()
}

